#!/usr/bin/env bash

echo "Building archive"
mkdir mono
cp -r /usr/* mono/
MONO_ARCHIVE=mono-$VERSION.tar.gz
tar -zcf $MONO_ARCHIVE mono
rm -rf /var/out/$MONO_ARCHIVE
mv $MONO_ARCHIVE /var/out/.

echo "Archive completed"

